from .EEGNet.CompactEEGNet import CompactEEGNet
from .SimSiam.SimSiam import SimSiam
from .SSLClassifier.SSLClassifier import SSLClassifier
from .TimeDomainBasedCNN.TimeDomainBasedCNN import TimeDomainBasedCNN
from .Multitask import MultitaskSSVEP
from .Multitask import MultitaskSSVEPClassifier
from .ConvCA import ConvCA
from .ConvCA import ConvCaLighting
from .DeepConvNet import DeepConvNet